heat_template_version: 2021-04-16

parameters:
  external:
    type: string
    default: provider2
  flavor:
    type: string
    default: m1.small
  internal_network_cidr:
    type: string
    default: 10.214.218.0/24
  internal_name:
    type: string
    default: internal-network

resources:
  server:
    type: OS::Nova::Server
    properties:
      image: ubuntu-jammy
      flavor: "m1.small"
      availability_zone: nova 
      key_name: "fif-test"
      networks:
        - port: { get_resource: server_port }

  router:
    type: OS::Neutron::Router
    properties:
      external_gateway_info:
        network: {get_param: external}

  router_interface:
    type: OS::Neutron::RouterInterface
    properties:
      router_id: { get_resource: router }
      subnet_id: { get_resource: internal_subnet }

  internal_network:
    type: OS::Neutron::Net

  internal_subnet:
    type: OS::Neutron::Subnet
    properties:
      name: {get_param: internal_name}
      network: { get_resource: internal_network }
      cidr: {get_param: internal_network_cidr}
      
  port_security_group:
    type: OS::Neutron::SecurityGroup
    properties:
      name: allow-http
      rules:
         - { remote_ip_prefix: 0.0.0.0/0, direction: ingress, protocol: tcp, port_range_min: 80, port_range_max: 80}

  server_port:
    type: OS::Neutron::Port
    properties:
      network: {get_resource: internal_network}
      fixed_ips:
        - subnet: { get_resource: internal_subnet }
      security_groups:
        - { get_resource: port_security_group }
