heat_template_version: 2021-04-16
parameter:
  index:
    type: number

  key_param:
    type: string


resources:
  server: 
    type: "OS::Nova::Server"
    properties: 
      name: { list-join: ['-', ['server', {get_param: index} ] ] }
      networks: 
        - port: {get_resource: server1_port}
      flavor: "m1.small"
      image: "nginx-hostname"
      availability_zone: nova 
      key_name: {get_param: key_param}

## Creating Instance 1 Port ##
  server_port:
    type: OS::Neutron::Port
    properties:
      security_groups: 
        - {get_resource: security_group}
      network_id: { get_resource: int_network }
      fixed_ips:
        - subnet_id: { get_resource: int_subnet }